version: '3.7'

services:
  web:
    build: ./mediaportal
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mediaportal/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mediaportal
      - POSTGRES_PASSWORD=mediaportal123
      - POSTGRES_DB=mediaportal_dev
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  celery:
    build: ./mediaportal
    command: celery -A mediaportal worker -l info
    volumes:
      - ./mediaportal/:/usr/src/app/
    depends_on: 
      - db
      - redis

volumes: 
  postgres_data:
  redisdata:
