# Generated by Django 3.1.2 on 2020-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='audios',
            field=models.ManyToManyField(blank=True, to='core.ContentAudio'),
        ),
        migrations.AlterField(
            model_name='page',
            name='texts',
            field=models.ManyToManyField(blank=True, to='core.ContentText'),
        ),
        migrations.AlterField(
            model_name='page',
            name='videos',
            field=models.ManyToManyField(blank=True, to='core.ContentVideo'),
        ),
    ]
