# Generated by Django 3.1.2 on 2020-11-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contentaudio_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvideo',
            name='subtitles_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
