# Generated by Django 3.1.2 on 2020-11-04 10:43

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201104_0941'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='page',
            name='audios',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='core.ContentAudio'),
        ),
        AlterSortedManyToManyField(
            model_name='page',
            name='videos',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='core.ContentVideo'),
        ),
    ]
