# Generated by Django 3.1.2 on 2020-11-10 12:41

from django.db import migrations


def forwards_func(apps, schema_editor):
    ContentVideo = apps.get_model('core', 'ContentVideo')
    ContentAudio = apps.get_model('core', 'ContentAudio')
    ContentText = apps.get_model('core', 'ContentText')
    Page = apps.get_model('core', 'Page')
    video1 = ContentVideo.objects.create(
        title='Demo Video 1',
        video_url='http://u.rl/1.mp4',
        subtitles_url='http:/u.rl/1-subt.srt',
        counter=0)
    audio1 = ContentAudio.objects.create(
        title='Demo Audio 1',
        audio_url='http://u.rl/1.mp3',
        rate=320,
        counter=0
    )
    text1 = ContentText.objects.create(
        title='Demo Text 1',
        body='There is big content 1',
        counter=0
    )
    page1 = Page.objects.create(
        title='Demo page 1'
    )
    page1.videos.add(video1)
    page1.audios.add(audio1)
    page1.texts.add(text1)
    Page.objects.create(
        title='Demo page 2'
    )
    Page.objects.create(
        title='Demo page 3'
    )
    Page.objects.create(
        title='Demo page 4'
    )
    Page.objects.create(
        title='Demo page 5'
    )
    Page.objects.create(
        title='Demo page 6'
    )
    Page.objects.create(
        title='Demo page 7'
    )
    Page.objects.create(
        title='Demo page 8'
    )
    Page.objects.create(
        title='Demo page 9'
    )
    Page.objects.create(
        title='Demo page 10'
    )
    Page.objects.create(
        title='Demo page 11'
    )


def reverse_func(apps, schema_editor):
    ContentVideo = apps.get_model('core', 'ContentVideo')
    ContentAudio = apps.get_model('core', 'ContentAudio')
    ContentText = apps.get_model('core', 'ContentText')
    Page = apps.get_model('core', 'Page')
    ContentAudio.objects.filter(title__startswith='Demo').delete()
    ContentVideo.objects.filter(title__startswith='Demo').delete()
    ContentText.objects.filter(title__startswith='Demo').delete()
    Page.objects.filter(title__startswith='Demo').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201104_1043'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
